import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-slate-50 px-3 md:px-20 font-CircularMedium'>
        <section className='min-h-screen'>
          <nav className='pt-10 mb-12 flex justify-between'>
            <h1>getme.pizza</h1>
            <ul className='flex items-center'>
              <li className='mx-2  text-sm'>
                <Link href={"/"}>FAQ</Link>
              </li>
              <li className='mx-2  text-sm'>
                <Link href={"/"}>Explore</Link>
              </li>
              <li className='mx-2 bg-yellow-400 rounded-full text-sm px-4  py-2'>
                <Link href={"/"}>Sign up</Link>
              </li>
            </ul>
          </nav>

          <div>
            <h1 className='text-3xl font-bold text-center px-2 leading-10'>We can all use a slice of pizza sometimes...</h1>
            <p className='pt-8 px-2 py-4 text-center text-gray-800 font-Montserrat font-bold leading-7 text-lg'>It all started with the pizza, so get tipped the crypto way... with pizza of course.</p>
            <div className='mx-2 text-center py-4 rounded-full bg-white mb-4 text-lg'>
              <span>
                getme.pizza/
              </span>
              <input placeholder={"test"}></input>
            </div>
            
            
            <Link href='/'><div className='mx-2 bg-yellow-400 rounded-full text-lg  py-3 text-center'>Start my page</div></Link>
            <p className=' px-2 py-4 text-center text-gray-800 font-Montserrat font-bold leading-7 text-sm'>*It's free and takes only a minute.</p>
          </div>
        </section>
      </main>

      
    </div>
  )
}
