import Head from "next/head";
import Link from "next/link";
import Footer from "./components/footer";
import { firestore, userToJson } from "./libs/firebase";
import UsersFeed from "./components/UsersList";
import { TbHandClick } from "react-icons/tb";
import { GiTakeMyMoney } from "react-icons/gi";
import { GiCrossedChains } from "react-icons/gi";

// Set a limit for getting users to display to 10 for now.
const LIMIT = 10;

// Returns a users array as props from firestore based on the limit above.
export async function getServerSideProps() {
  const usersQuery = firestore.collection("users").limit(LIMIT);
  const users = (await usersQuery.get()).docs.map(userToJson);
  return {
    props: { users },
  };
}

/**`
 * Homepage takes in users array as props from getServerSideProps
 * @param  {Array} props
 */
export default function Home(props) {
  return (
    <div className='bg-slate-50'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='  font-CircularMedium lg:max-w-5xl lg:mx-auto'>
        <section className='px-3 md:px-20'>
          <div>
            <h1 className='text-3xl font-bold text-center px-2 py-2 leading-10 md:text-4xl md:max-w-lg mx-auto lg:max-w-4xl lg:text-6xl lg:pt-14 '>
              We can all use a slice of 🍕 sometimes...
            </h1>
            <p className='pt-8 px-2 py-8 max-w-sm mx-auto text-center text-gray-800 font-Montserrat font-bold leading-7 text-lg md:text-xl md:max-w-md lg:max-w-4xl lg:text-2xl lg:px-40'>
              It all started with the pizza, so get tipped the crypto way...
              with pizza of course.
            </p>
            <div className='mx-2 text-center py-4 rounded-full bg-white mb-4 text-lg lg:max-w-lg lg:mx-auto'>
              <span className=''>getme.pizza/</span>
              <input
                type={"text"}
                className='pl-0 border-none focus:ring-0'
                placeholder={"yourname"}
              ></input>
              <span className='hidden  lg:inline'>
                <Link href='/enter'>
                  <a className='px-6 bg-yellow-400 cursor-pointer rounded-full text-lg  py-3 text-center   hover:text-xl hover:bg-orange-400 transition-all'>
                    Start my page
                  </a>
                </Link>
              </span>
            </div>

            <Link href='/enter'>
              <div className='mx-2 bg-yellow-400 rounded-full text-lg  py-3 text-center lg:hidden'>
                Start my page
              </div>
            </Link>
            <p className=' px-2 py-4 text-center text-gray-800 font-Montserrat font-bold leading-7 text-sm'>
              *It's free and takes only a minute.
            </p>
          </div>
        </section>

        {/* Creators Section */}
        <section className='px-3 md:px-20'>
          <h1>LATEST CREATORS</h1>

          <nav className='pt-1 mb-5'>
            <ul className='flex items-center overflow-x-auto scrollbar-hide snap-x scroll-auto'>
              <UsersFeed users={props} />
            </ul>
          </nav>
        </section>

        {/* Info Section */}
        <section className='bg-yellow-50 pb-10 rounded-3xl '>
          <div className='px-3 md:px-20'>
            <h4 className='text-center pt-10 text-gray-500 pb-5 tracking-wide'>
              TIP
            </h4>
            <h2 className='text-3xl font-bold text-center px-2 leading-10 pb-5'>
              Give your followers a way to say wagmi.
            </h2>
            <p className='pt-8 px-2 py-4 text-center text-gray-800 font-Montserrat font-bold leading-7 text-lg'>
              GetMe.Pizza makes supporting pretty awesome. With just a click,
              your followers can tip you enough crypto to get yourself a 🍕
              slice! They can leave a message and not even have to create an
              account.
            </p>
          </div>

          <div className='px-3 md:px-20'>
            <p className='pt-8 px-2 py-4 text-center text-gray-800 font-Montserrat font-bold leading-7 text-lg'>
              Membership tools and ways to sell your digital items easily are
              coming soon...
            </p>
          </div>
        </section>

        {/* Action Section */}
        <section className='pt-10 mb-5'>
          <h2 className='text-3xl font-bold text-center px-2 leading-10 py-5'>
            Made for web3 creators
          </h2>
          <div className='pt-8 '>
            <TbHandClick className='mb-4 mx-auto text-center text-4xl text-orange-500' />
            <p className='mx-auto text-center max-w-[250px] font-Montserrat text-sm'>
              Set up your account and allow your{" "}
              <span className='font-CircularMedium  '>fans</span> to support{" "}
              <span className='font-CircularMedium  '>you</span>.
            </p>
          </div>
          <div className='pt-8'>
            <GiTakeMyMoney className='mb-4 mx-auto text-center text-4xl text-orange-500' />
            <p className='mx-auto text-center max-w-[250px] font-Montserrat text-sm'>
              You will get your crypto paid out{" "}
              <span className='font-CircularMedium  '>instantly</span>, while
              your supporter will get an NFT as a momento.
            </p>
          </div>
          <div className='pt-8 pb-10'>
            <GiCrossedChains className='mb-4 mx-auto text-center text-4xl text-orange-500' />
            <p className=' mx-auto text-center max-w-[250px] font-Montserrat text-sm'>
              Tips and memo's are{" "}
              <span className='font-CircularMedium  '>transparent</span> and{" "}
              <span className='font-CircularMedium  '>on-chain</span>.
            </p>
          </div>
          <div className='text-center h-[50px]'>
            <Link href='/enter'>
              <a className='mx-10 bg-yellow-400 rounded-full  py-3 px-10  cursor-pointer md:max-w-xs md:mx-auto  hover:text-xl hover:bg-orange-400 transition-all'>
                Start my page
              </a>
            </Link>
          </div>

          <p className=' px-2 py-2 text-center text-gray-800 font-Montserrat font-bold leading-7 text-xs'>
            *It's free and takes only a minute.
          </p>
        </section>

        <Footer />
      </main>
    </div>
  );
}
